### PR TITLE
Don't fail cleanup if internalrequests not installed

### PR DESCRIPTION
**Pull request by ralphbean**
This is the case on the new Fedora Cluster run by the [Konflux+Fedora SIG](https://github.com/konflux-ci/community/blob/main/sigs/fedora.md)

### CODE REVIEW

**Comment by ralphbean** [comment]
This should help fix https://github.com/konflux-ci/release-service/issues/589

**Review by mmalina — APPROVED** [review]

**Review by johnbieren — APPROVED** [review]

**Comment by happybhati** [comment]
It needs a quick rebase from development!
Code LGTM!

**Comment by johnbieren** [comment]
@ralphbean can you rebase this so we can merge it?

**Comment by johnbieren** [comment]
E2E is broken. We have been discussing it on our team channel. I don't know how the e2e breaking prs passed e2e and got merged, but that is the state we are in

**Comment by johnbieren** [comment]
Only the rh-push-to-registry-redhat-io test failed and it failed on the run-file-updates task, which isn't related to this change. Merging

**Pull request merged**
