### PR TITLE
fix(EC-722): provide timeout param for ec validation

### PR DESCRIPTION
**Pull request by ralphbean**
Depends on https://github.com/enterprise-contract/ec-cli/pull/1754

### CODE REVIEW

**Review by johnbieren — DISMISSED** [review]

**Review by happybhati — DISMISSED** [review]
/lgtm

**Comment by jinqi7** [comment]
Currently, there is a known issue in CI - see [slack](https://redhat-internal.slack.com/archives/C02FANRBZQD/p1720776206678809?thread_ts=1720775899.080709&cid=C02FANRBZQD).

**Comment by ralphbean** [comment]
Ack, thank you. https://github.com/codeready-toolchain/toolchain-e2e/pull/1013 merged one hour ago now. Let's try again.

**Comment by johnbieren** [comment]
/test release-pipelines-e2e-suite
@ralphbean it looks like your commit isn't signed

**Review by johnbieren — DISMISSED** [review]

**Review by johnbieren — APPROVED** [review]

**Pull request merged**
