### PR TITLE
fix(RELEASE-1339): no longer consult .sign.request

### PR DESCRIPTION
**Pull request by scoheb**
## Describe your changes
- use the sign-base64-blob task default for the request pipeline name

## Relevant Jira
- [RELEASE-1339](https://issues.redhat.com//browse/RELEASE-1339)

## Checklist before requesting a review
- [x] I have marked as draft or added `do not merge` label if there's a dependency PR
  - If you want reviews on your draft PR, you can add reviewers or add the `release-service-maintainers` handle if you are unsure who to tag
- [x] My commit message includes `Signed-off-by: My name <email>`
- [x] I have bumped the task/pipeline version string and updated changelog in the relevant README
- [x] I read CONTRIBUTING.MD and [commit formatting](CONTRIBUTING.md#commit-message-formatting-and-standards)

### CODE REVIEW

**Review by johnbieren — COMMENTED** [review]
What do you think about going one step farther and removing the `request` parameter and hardcoding the value in the task yaml?

**Comment by scoheb** [comment]
> What do you think about going one step farther and removing the `request` parameter and hardcoding the value in the task yaml?

done

**Review by johnbieren — APPROVED** [review]

**Comment by scoheb** [comment]
e2e test failing in FBC which does not use this task. force merging.

**Pull request merged**
