### PR TITLE
chore: bump release-service-utils in apply-mapping

### PR DESCRIPTION
**Pull request by jbpratt**
bump to the latest version available

Signed-off-by: Brady Pratt <bpratt@redhat.com>

### CODE REVIEW

**Review by johnbieren — APPROVED** [review]
/ok-to-test

**Comment by johnbieren** [comment]
@jbpratt can you rebase this so we can merge it?

**Comment by johnbieren** [comment]
Sorry @jbpratt gonna need another rebase

**Review by johnbieren — APPROVED** [review]

**Comment by johnbieren** [comment]
E2E seems to have flaked on you (judging by how long it is taking) and it passed on another PR that was merged so will need another rebase here unfortunately

**Comment by jbpratt** [comment]
> E2E seems to have flaked on you (judging by how long it is taking) and it passed on another PR that was merged so will need another rebase here unfortunately

rebased! No worries

**Comment by jbpratt** [comment]
rebased again

**Pull request merged**
