### PR TITLE
feat(RELEASE-1336): skip image layers in Pyxis with skipLayers

### PR DESCRIPTION
**Pull request by mmalina**
A new option is added to data file to be able to skip layer details when create Pyxis image.

This was previously created as a one-off workaround to unblock bootc releases here:
https://github.com/konflux-ci/release-service-catalog/pull/684

Now it's an option that can be enabled as needed.

For full explanation, see the jira and also the comment in the task script.

### CODE REVIEW

**Review by ralphbean — APPROVED** [review]

**Comment by johnbieren** [comment]
This needs rebase @mmalina 
Very strange the e2e still hasn't finished for it though.
I don't know as much about this as you two so I will let Ralph's approval be enough

**Comment by mmalina** [comment]
> This needs rebase @mmalina Very strange the e2e still hasn't finished for it though. I don't know as much about this as you two so I will let Ralph's approval be enough

I was kind of waiting for your review, so thanks for the note. Rebased now.

**Comment by mmalina** [comment]
@johnbieren actually, maybe you can at least quickly check the param change to see if I missed a version bump or something? It's always good to have an extra pair of eyes on it and I don't think Ralph checked that :)

**Comment by johnbieren** [comment]
> @johnbieren actually, maybe you can at least quickly check the param change to see if I missed a version bump or something? It's always good to have an extra pair of eyes on it and I don't think Ralph checked that :)

Will do today

**Review by johnbieren — APPROVED** [review]

**Pull request merged**
