### PR TITLE
fix(RHTAPREL-857): update release-utils image

### PR DESCRIPTION
**Pull request by theflockers**
This PR updates the release-service-utils image to the latest that contains the fix for [RHTAPREL-857](https://issues.redhat.com//browse/RHTAPREL-857).

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

### CODE REVIEW

**Review by mmalina — APPROVED** [review]

**Review by mmalina — APPROVED** [review]

**Comment by johnbieren** [comment]
If you search https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-appstudio_release-service-catalog/366/pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite/1763005092761440256/artifacts/release-pipelines-e2e-suite/redhat-appstudio-gather/artifacts/taskruns.json for `"Failed"` you will see the one task that failed was `push-sbom-to-pyxis` so maybe the change isn't actually good? But what is confusing is in the same file, if you search for `push-sbom-to-pyxis`, you see another taskrun and that one actually succeeded. I am not sure what is going on with CI. Going to trigger it one more time but I won't be online when it finishes

**Comment by mmalina** [comment]
> If you search https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-appstudio_release-service-catalog/366/pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite/1763005092761440256/artifacts/release-pipelines-e2e-suite/redhat-appstudio-gather/artifacts/taskruns.json for `"Failed"` you will see the one task that failed was `push-sbom-to-pyxis` so maybe the change isn't actually good? But what is confusing is in the same file, if you search for `push-sbom-to-pyxis`, you see another taskrun and that one actually succeeded. I am not sure what is going on with CI. Going to trigger it one more time but I won't be online when it finishes

Good catch. Here's the pod log: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/redhat-appstudio_release-service-catalog/366/pull-ci-redhat-appstudio-release-service-catalog-development-release-pipelines-e2e-suite/1763005092761440256/artifacts/release-pipelines-e2e-suite/gather-extra/artifacts/pods/push-pyxis-managed-rsre_managed-c6g95-push-sbom-to-pyxis-pod_step-push-sbom-files-to-pyxis.log
```
=== 65dfdc5b3ce9e6dc66517873.json ===
Traceback (most recent call last):
  File "/home/pyxis/upload_sbom", line 366, in <module>
    main()
  File "/home/pyxis/upload_sbom", line 360, in main
    upload_sbom_with_retry(args.pyxis_graphql_api, image_id, args.sbom_path)
  File "/home/pyxis/upload_sbom", line 85, in upload_sbom_with_retry
    upload_sbom(graphql_api, image_id, sbom_path)
  File "/home/pyxis/upload_sbom", line 95, in upload_sbom
    image = get_image(graphql_api, image_id)
  File "/home/pyxis/upload_sbom", line 201, in get_image
    components.extend(components_batch)
TypeError: 'NoneType' object is not iterable
```
Which actually looks like the thing that we were trying to fix. But in this case it happens for the image that was already processed in the previous PipelineRun. So I ran the sbom script locally and it turns out that stage Pyxis is having the same issue as when all of this started - "Pyxis API was unable to fetch data from MongoDB in time". I commented on the GChat thread.

**Comment by mmalina** [comment]
Stage Pyxis should be fixed now. Rerunning the tests.

**Comment by johnbieren** [comment]
/test release-pipelines-e2e-suite
No pipelineruns or taskruns in the artifacts

**Pull request merged**
