### PR TITLE
fix: update author name to red-hat-konflux[bot]

### PR DESCRIPTION
**Pull request by jinqi7**
The whole value of the author should be "red-hat-konflux[bot]" instead of "red-hat-konflux"

### CODE REVIEW

**Review by mmalina — COMMENTED** [review]
Can you explain the change in the commit message? I can only guess that if https://github.com/konflux-ci/konflux-qe-definitions/pull/66 is merged, this will cause the author to be different, but I don't know for sure. Please always explain in the commit message/PR description why a change is made.

**Comment by jinqi7** [comment]
> Can you explain the change in the commit message? I can only guess that if [konflux-ci/konflux-qe-definitions#66](https://github.com/konflux-ci/konflux-qe-definitions/pull/66) is merged, this will cause the author to be different, but I don't know for sure. Please always explain in the commit message/PR description why a change is made.

Update!

**Comment by mmalina** [comment]
> > Can you explain the change in the commit message? I can only guess that if [konflux-ci/konflux-qe-definitions#66](https://github.com/konflux-ci/konflux-qe-definitions/pull/66) is merged, this will cause the author to be different, but I don't know for sure. Please always explain in the commit message/PR description why a change is made.
> 
> Update!

I still don't understand... Now you removed the linked PR. So it's not related? So it never worked?

**Comment by jinqi7** [comment]
> > > Can you explain the change in the commit message? I can only guess that if [konflux-ci/konflux-qe-definitions#66](https://github.com/konflux-ci/konflux-qe-definitions/pull/66) is merged, this will cause the author to be different, but I don't know for sure. Please always explain in the commit message/PR description why a change is made.
> > 
> > 
> > Update!
> 
> I still don't understand... Now you removed the linked PR. So it's not related? So it never worked?

It didn't work before. But it depends on PR #66 to get the real value for the condition check.

**Review by mmalina — DISMISSED** [review]

**Review by psturc — CHANGES_REQUESTED** [review]
in order to use the updated task from https://github.com/konflux-ci/konflux-qe-definitions/pull/66, you have to change the version to `0.2` [here](https://github.com/konflux-ci/release-service-catalog/pull/657/files#diff-b95cbbb0088e1a08e6e3983fd72cf84eeeb1b822379e1fa092fcc4c9dd0cddc4R68)

**Review by johnbieren — APPROVED** [review]

**Pull request merged**
