### PR TITLE
fix(KFLUXBUGS-1172): update release-service-utils image ref in all tasks

### PR DESCRIPTION
**Pull request by scoheb**
- use new release-service-utils image pullspec

### CODE REVIEW

**Review by johnbieren — COMMENTED** [review]
I don't think the commit title is an accurate description of the change. Yes, the new image may have fixed a client error when creating the pyxis image, but every single release-utils image ref was updated in the commit. I think it would make more sense to have like `fix(KFLUXBUGS-1172): update release-service-utils image ref in all tasks` or something. Because 90% or more of the changes here have nothing to do with pyxis

**Comment by scoheb** [comment]
> I don't think the commit title is an accurate description of the change. Yes, the new image may have fixed a client error when creating the pyxis image, but every single release-utils image ref was updated in the commit. I think it would make more sense to have like `fix([KFLUXBUGS-1172](https://issues.redhat.com//browse/KFLUXBUGS-1172)): update release-service-utils image ref in all tasks` or something. Because 90% or more of the changes here have nothing to do with pyxis

updated PR title and commit

**Review by johnbieren — APPROVED** [review]

**Pull request merged**
