### PR TITLE
fix(RELEASE-1063): linting issues in collect-slack-notification-params

### PR DESCRIPTION
**Pull request by theflockers**
this commit fixes the linting issues present in
the collect-slack-notification-params task

    Signed-off-by: Leandro Mendes <lmendes@redhat.com>

### CODE REVIEW

**Review by johnbieren — CHANGES_REQUESTED** [review]
Changes look fine, but can you bump the z of the version and add a README entry? The other PRs doing the same do that

**Comment by theflockers** [comment]
> Changes look fine, but can you bump the z of the version and add a README entry? The other PRs doing the same do that

done!

**Review by johnbieren — APPROVED** [review]

**Review by happybhati — APPROVED** [review]

**Review by mmalina — APPROVED** [review]

**Pull request merged**
