### PR TITLE
fix: update the schema to add closing brackets

### PR DESCRIPTION
**Pull request by seanconroy2021**
This updated the schema to add closing
 brackets to contentGateway.components

### CODE REVIEW

**Review by jinqi7 — APPROVED** [review]

**Review by theflockers — APPROVED** [review]
crazy how the other PR did not fail tests with so many missing brackets.

**Comment by jinqi7** [comment]
> crazy how the other PR did not fail tests with so many missing brackets.

Some PRs failed for other errors before running into this issue. We haven't merged a PR this week.

**Review by mmalina — APPROVED** [review]

**Comment by seanconroy2021** [comment]
> crazy how the other PR did not fail tests with so many missing brackets.

E2E failed on the [PR](https://github.com/konflux-ci/release-service-catalog/pull/680#issuecomment-2473163896)

**Comment by mmalina** [comment]
> > crazy how the other PR did not fail tests with so many missing brackets.
> 
> Some PRs failed for other errors before running into this issue. We haven't merged a PR this week.

I think Leandro meant the PR where the breaking change got merged. But it never ran e2e: https://github.com/konflux-ci/release-service-catalog/pull/680#event-15339875086

**Comment by seanconroy2021** [comment]
I think we should add a  workflow to validate the schema would prevent this from happening again

**Comment by mmalina** [comment]
> I think we should add a workflow to validate the schema would prevent this from happening again

Adding here: https://github.com/konflux-ci/release-service-catalog/pull/697

**Pull request merged**
