### PR TITLE
chore:  ignore tekton files by yamllint

### PR DESCRIPTION
**Pull request by jinqi7**

### CODE REVIEW

**Review by seanconroy2021 — DISMISSED** [review]
lgtm

**Review by mmalina — CHANGES_REQUESTED** [review]
Please remove the extra 6 commits that don't belong here.

**Review by johnbieren — COMMENTED** [review]
Can you update the commit message? Update yamllint doesn't really tell me much at all (I thought the PR would be updating a yamllint version before I opened it). There is no context about ignoring a new directory generated after onboarding to konflux

**Review by johnbieren — APPROVED** [review]

**Comment by johnbieren** [comment]
Merging without e2e because e2e has nothing to do with this and this is blocking other PRs

**Pull request merged**
