### PR TITLE
revert(ISV-5125): add unique tag info to purl

### PR DESCRIPTION
**Pull request by theflockers**
this commit reverts the PR #548

Signed-off-by: Leandro Mendes <lmendes@redhat.com>

### CODE REVIEW

**Comment by theflockers** [comment]
PR was unnecessary.

**Comment by wcheang** [comment]
@theflockers why was this deemed unnecessary? The updated purl with tag info was needed as part of the release-time sbom work (epic: https://issues.redhat.com/browse/CLOUDWF-10461). In isolation the info doesn't seem to be used yet, but we have ongoing and future tasks that will use that to augment existing component-level sboms and create new product-level ones.

**Comment by johnbieren** [comment]
> @theflockers why was this deemed unnecessary? The updated purl with tag info was needed as part of the release-time sbom work (epic: https://issues.redhat.com/browse/CLOUDWF-10461). In isolation the info doesn't seem to be used yet, but we have ongoing and future tasks that will use that to augment existing component-level sboms and create new product-level ones.

Leandro opened this to readd the changes in case we reverted our production branch. We didn't revert our production branch, so this wasn't needed... the code is still in production https://github.com/konflux-ci/release-service-catalog/commit/31441323411844af5a6951126f0e71dfd172dcdb

**Comment by wcheang** [comment]
> Leandro opened this to readd the changes in case we reverted our production branch. We didn't revert our production branch, so this wasn't needed... the code is still in production [3144132](https://github.com/konflux-ci/release-service-catalog/commit/31441323411844af5a6951126f0e71dfd172dcdb)

I see, thanks for the clarification!

**Pull request closed without merging**
